name: money_calc_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  top_snackbar_flutter: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  uuid: ^3.0.5
  intl: ^0.17.0
  giff_dialog: ^1.0.1
  rxdart: ^0.27.3
  admob_flutter: ^2.0.0
  provider: ^6.0.2
  shrink_sidemenu: ^2.0.0+2-null-safety
  in_app_review: ^2.0.4
  url_launcher: ^6.0.18
  eva_icons_flutter: ^3.0.2
  webview_flutter: ^3.0.0
  get: ^4.6.1
  glassmorphism: ^3.0.0
  shared_preferences: ^2.0.13
  holding_gesture: ^1.1.0
  math_expressions: ^2.3.0
  enum_to_string: ^2.0.1
  app_tracking_transparency: ^2.0.2+1
  sqflite: ^2.0.2
  path_provider: ^2.0.9

  #TODO 後で戻したいやつ
  # package_info_plus: ^1.2.0
  # flutter_local_notifications:



  #admob
  #google_mobile_ads: ^1.0.1
  #google_mobile_ads: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/3.png
    - assets/images/background.png
    - assets/images/gif.gif
    - assets/images/dialog.gif
    - assets/images/icon_man.png
    - assets/images/icon_woman.png
    - assets/background.gif
