name: money_calc_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  top_snackbar_flutter: ^1.0.2

  admob_flutter: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  uuid: ^3.0.5
  intl: ^0.17.0
  giff_dialog: ^1.0.1
  rxdart: ^0.27.3
  google_mobile_ads: ^0.12.0
  provider: ^6.0.2
  flutter_local_notifications: ^9.2.0

  intl_phone_number_input:
  shrink_sidemenu: ^2.0.0+2-null-safety
  in_app_review: ^2.0.4


  #admob
  #google_mobile_ads: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  shared_preferences:
  holding_gesture:
  math_expressions:
  enum_to_string:

  sqflite:
  path_provider:

  app_tracking_transparency:

  freezed:
  flutter_state_notifier:
  state_notifier:
  build_runner:
flutter:
  uses-material-design: true
  assets:
   - assets/images/3.png
   - assets/images/gif.gif
   - assets/images/dialog.gif
   - assets/images/icon_man.png
   - assets/images/icon_woman.png
